[package]
name = "bedder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bedder"
path = "src/lib.rs"

[[bin]]
name = "bedder"
path = "src/main.rs"


[dependencies]
rand = "0.8.5"
smartstring = {version = "1.0.1", optional = true }
smol_str = {version = "0.2.0", optional = true }
compact_str = {version = "0.7.0", optional = true }
kstring = {version = "2.0.0", optional = true }
noodles = {version = "0.39.0"}
flate2 = "1.0.26"
clap = {version="4.2.7", features=['derive']}
env_logger = "0.10.0"
log = "0.4.19"

[features]
default = ["bed", "vcf", "bcf", "csi", "core", "bam", "sam"]
bed = ["noodles/bed"]
bam = ["noodles/bam"]
#cram = ["noodles/cram"]
sam = ["noodles/sam"]
vcf = ["noodles/vcf"]
csi = ["noodles/csi"]
core = ["noodles/core"]
bcf = ["noodles/bcf"]


[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
clap = {version = "4.2.7", features=["derive"]}

[[bench]]
name = "random_intervals"
harness = false

[profile.release]
lto = true

